name: all_pnud
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:        # ✅ nécessaire pour la traduction
    sdk: flutter
  intl: ^0.20.2                 # ✅ gestion des formats (date, nombres, etc.)
  provider: ^6.1.2              # State management
  shared_preferences: ^2.2.3    # Stockage local (mode dark, langue, etc.)
  go_router: ^16.2.0            # Navigation
  http: ^1.2.1                  # Requêtes API
  jwt_decoder: ^2.0.1           # Décodage JWT
  image_picker: ^1.2.0          # Sélection d’images
  # easy_localization: ^3.0.5     # ✅ Internationalisation simplifiée
  file_selector: ^0.9.1
  flutter_map: ^8.2.1       # <-- mise à jour
  latlong2: ^0.9.1            # ✅ Gestion des coordonnées GPS
  geolocator: ^12.0.0
  qr_code_scanner_plus: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/pnud.png
    - assets/images/app_logo.png  # Nouveau logo app
    - assets/images/scan.png
    - assets/images/user.jpg
    - assets/images/
    # Ajouter d'autres images si nécessaire
