name: all_pnud
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^16.2.0
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.0
  file_selector: ^0.9.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  qr_code_scanner_plus: ^2.0.12
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ Ajouté ici

# Configuration du package pour générer les icônes
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"  # ✅ ton logo principal

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/pnud.png
    - assets/images/app_logo.png
    - assets/images/scan.png
    - assets/images/user.jpg
    - assets/images/
